version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "9889:80"
        volumes:
            - /var/lib/jenkins/workspace/test/project_work_11:/var/www
            - ./logs/nginx:/var/log/nginx
